myDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include('pease.urls'))
]
if settings.DEBUG:
    print(f'hellow sk')
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pease/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from pease import views

urlpatterns = [
    path('test',views.test, name='test'),
    path('emp',views.emp, name='emp'),
    path('show',views.show, name='show'),
    path('edit/<int:id>',views.edit, name='edit'),
    path('update/<int:id>',views.update, name='update'),
    path('delete/<int:id>',views.destroy, name='delete'),
    path('register', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='employee/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='employee/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='employee/pass_rest.html'), 
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='employee/pass_rest_done.html'), 
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
            auth_views.PasswordResetConfirmView.as_view(template_name='employee/pass_rest_conf.html'), 
            name='password_reset_confirm'),       
    path('password-reset-complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name='employee/pass_rest_complete.html'), 
            name='password_reset_complete'),     
    path('profile',views.profile,name='profile')
    

] 

pease/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.
class Employee(models.Model):
    eid = models.CharField(max_length=30)
    ename = models.CharField(max_length=30)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table = "employee"
class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    

    def __str__(self):
        return self.first_name

class Company(models.Model):
    name=models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    date_created = models.DateField()

    def __str__(self):
        return self.name
        
class Language(models.Model):
    name=models.CharField(max_length=20)
    creator = models.CharField(max_length=30)
    paradigm = models.CharField(max_length=30)
    date_created = models.DateField()
    def __str__(self):
        return self.name

class Programmer(models.Model):
    name=models.CharField(max_length=30)
    age = models.IntegerField()
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    languages = models.ManyToManyField(Language)
    def __str__(self):
        return self.name

#Profile page Extending existing user model
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size =(300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

pease/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from pease.models import Employee, Profile
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

pease/views.py
from django.shortcuts import render, redirect
from pease.forms import EmployeeForm, UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from pease.models import Employee
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def test(request):
    context = {'content':"hello Sikander....!"}
    return render(request, 'base/base.html',context)

@login_required
def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                ename = form.cleaned_data.get('ename')
                messages.success(request, f' {ename} has been added!')
                return redirect('/employee/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'employee/index.html',{'form':form})

def show(request):
    employees = Employee.objects.all()
    return render(request, 'employee/show.html',{'employees':employees})

@login_required
def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'employee/edit.html',{'employee':employee})

@login_required
def update(request, id):
    employee = Employee.objects.get(id = id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        ename = form.cleaned_data.get('ename')
        messages.success(request, f'Record updated for {ename}')
        return redirect("/employee/show")
    return render(request, 'employee/edit.html',{'employee':employee})

@login_required
def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/employee/show")


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Successfully created account for {username}!')
            
            return redirect('login')
            
    else:
        form= UserRegisterForm()
    
    
    return render(request, 'employee/register.html',{'form':form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form=UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Successfully updated profile and user')
            return redirect('profile')
    else:
        u_form=UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request,'employee/profile.html',context)

pease/templates/base/adv.html
<div class="jumbotron text-center" style="margin-bottom:0">
    {% block adv %}
    <h1>{{content}}</h1>
    <p>Resize this responsive page to see the effect!</p> 
    {% endblock %}
  </div>

pease/templates/base/base.html
     {% include 'base/header.html' %}      
     <title>{% block title %}sikander {% endblock %}</title>
     {% block style_tag %}
     <style>
     .fakeimg {
  height: 200px;
  background: #aaa;
};
a:link, a:visited {
    color: white;
    text-align: center;
    text-decoration: none;
    display: inline-block;
  };
 a:active, a:hover {
   padding: 3px;
  };
      </style>
    {% endblock %}
    </head>
    <body>  
     {% include 'base/navbar.html' %}
      
      <div class="container" style="margin-top:30px">
        <div class="row">
        
       
          <div class="col-sm-8">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}
            <h2>TITLE HEADING</h2>
            <h5>Title description, Dec 7, 2017</h5>
            <div class="fakeimg">Fake Image</div>
            <p>Some text..</p>
            <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
            <br>
            <h2>TITLE HEADING</h2>
            <h5>Title description, Sep 2, 2017</h5>
            <div class="fakeimg">Fake Image</div>
            <p>Some text..</p>
            <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
            {% endblock %}
          </div>
        
        </div>
      </div>
      
  {% include 'base/footer.html' %}
  

pease/templates/base/footer.html
<div class="jumbotron text-center" style="margin-bottom:0; margin-top: 10px;">
  <h6>&copy; <span id='sk_date'></span> | All rights reserved </h6>
  </div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script>
  var d = new Date();
 document.getElementById("sk_date").innerHTML = d.getFullYear();
 </script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

pease/templates/base/header.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css\employee\style.css' %}">

pease/templates/base/navbar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
        <a class="navbar-brand" href="#">Sk App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
   
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'show' %}">Employees</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Todo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Blog</a>
        </li>    
      </ul>

      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
        <a class="nav-item nav-link" href="{% url 'logout' %}">Log  Out</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        {% endif %}
      </div>
    </div>

    </div>  
  </nav>

pease/templates/base/sidebar.html
<div class="col-sm-4">
    <h2>About Me</h2>
    <h5>Photo of me:</h5>
    <div class="fakeimg">Fake Image</div>
    <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    <h3>Some Links</h3>
    <p>Lorem ipsum dolor sit ame.</p>
    {% block sidebar %}
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">TO DO </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Blog</a>
      </li>
     
    </ul>
    {% endblock %}
    <hr class="d-sm-none">
  </div>

pease/templates/employee/edit.html
{% extends 'base/base.html' %}
{% block title %}Update Record {% endblock %}
{% block content %}
<form method="POST" class="post-form" action="/employee/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock %}

pease/templates/employee/index.html
{% extends 'base/base.html' %}
{% block title %}Add Employee {% endblock %}
{% block content %}
<form method="POST" class="post-form" action="/employee/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock %}

pease/templates/employee/login.html
l{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register Page {% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="from-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted">
                   Forget Password? <a class="ml-2" href="{% url 'password_reset' %}">Reset Password</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Create an Account ? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

pease/templates/employee/logout.html
l{% extends 'base/base.html' %}

{% block title %}Register Page {% endblock %}
{% block content %}
    <h2>
        You have been logged out
    </h2>
    <div class="border-top pt-3">
        <small class="text-muted">
       <a  href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock %}

pease/templates/employee/pass_rest.html
l{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register Page {% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="from-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
   
{% endblock %}

pease/templates/employee/pass_rest_complete.html
{% extends 'base/base.html' %}

{% block title %}Password Set {% endblock %}
{% block content %}
    <div class="alert alert-info">
        Congratulation.Your password has been set.
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
       <a  href="{% url 'login' %}">Log In Here</a>
        </small>
    </div>
{% endblock %}

pease/templates/employee/pass_rest_conf.html
l{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register Page {% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="from-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
   
{% endblock %}

pease/templates/employee/pass_rest_done.html
{% extends 'base/base.html' %}

{% block title %}Verification {% endblock %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instruction to your mail
    </div>
{% endblock %}

pease/templates/employee/profile.html
l{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register Page {% endblock %}
{% block content %}
<div class="content-section">
   <div class="media">
     <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
     <div class="media-body">
       <h2 class="account-heading">{{ user.username }}</h2>
       <p class="text-secondary">{{ user.email }}</p>
     </div>
   </div>
   <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <fieldset class="from-group">
                <legend class="border-bottom mb-4"> Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
{% endblock %}

pease/templates/employee/register.html
l{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register Page {% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="from-group">
                <legend class="border-bottom mb-4"> Sign Up Now</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an Account ? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
{% endblock %}

pease/templates/employee/show.html
{% extends 'base/base.html' %}
{% block title %}Employee Records {% endblock %}
{% block content %}
<div class="table-responsive">
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <span class="badge badge-success"> <a href="/employee/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  </span>
            <span class="badge badge-danger"><a href="/employee/delete/{{ employee.id }}">Delete</a></span>
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
</div>
<br>  

<center><a href="/employee/emp" class="btn btn-primary">Add New Record</a></center>  
{% endblock %}